name: Run process through VPN

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-process-vpn:
    name: Run process through VPN
    runs-on: teste
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Run process only after VPN is connected
        run: python siafi_automacao/cota_orcamentaria.py
